# Generated by Django 2.2.5 on 2019-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
