# Generated by Django 2.2.5 on 2019-10-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0005_auto_20191001_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated_at', '-timestamp']},
        ),
    ]
