# Generated by Django 2.2.5 on 2019-10-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0006_auto_20191001_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['publish_date', 'updated_at', 'timestamp']},
        ),
    ]
